version: "3.9"

# Usage:
## Start up all services:
### docker-compose -f docker/docker-compose.yml up -d
## -f flag to specify the filename if filename is not docker-compose.yml or if it's not located in the current directory.
## -d flag is used to detach the container's output from the terminal so you can keep using the same terminal.
## Shutdown all services:
### docker-compose -f docker/docker-compose.yml down
## -f flag to specify the filename if filename is not docker-compose.yml or if it's not located in the current directory.
services:
    # BACKUP MYSQL by generating dump file
    # docker exec CONTAINER-NAME mysqldump -u root --password=root DATABASE-NAME > backup.sql
    # RESTORE MYSQL from dump file
    # docker exec -i CONTAINER-NAME mysql -u root --password=root DATABASE-NAME < backup.sql
    db-hackaton:
        container_name: db-hackaton
        image: mysql:5.7
        restart: always
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        env_file:
            - ../.env
        ports:
            - target: 3306
              published: 3306
              protocol: tcp
              mode: host
